version: "3.9"
services:
  swapi:
    build:
      context: .
      dockerfile: swapi/Dockerfile
      target: dev
    command: npm start
    restart: unless-stopped
    volumes:
      - ./swapi/:/usr/swapi
      - /usr/swapi/node_modules
    ports:
      - ${SWAPI_PORT:-8080}:8080
    environment:
      - PORT=8080

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      target: dev
    command: npm start
    restart: unless-stopped
    depends_on:
      - swapi
    ports:
      - ${CLIENT_PORT:-3000}:3000
    volumes:
      - ./client/:/usr/client
      - /usr/client/node_modules
